### ISSUE TITLE
Auto Refresh Functionality Similar to reflector.timer

### ISSUE THREAD

**Issue by xrhstosmour** [westandskif/rate-mirrors#54]
Hello,

Firstly, I'd like to express my appreciation for your project. It's been incredibly useful.

I have a question regarding the availability of an auto refresh feature. In particular, I'm interested in something akin to the `reflector.timer` functionality. Could you please inform me if such a feature exists in your project, or if there are plans to include it in the future?

Thanks in advance.

**Comment by westandskif** [comment]
Hi! Thank you for kind words! I'll have a look at this once more on ~ Sun.
My current concern is: _imagine your mirrors were updated at 8 AM by the timer and 5 hours later you need to install something new along with a system update. What if the mirror on top of your mirrorlist, which is at this point 5 hours old, is now in the middle of syncing?_

**Comment by xrhstosmour** [comment]
I understand your concern!
I am not sure how the refresh functionality actually works though, I will look through it and maybe come back.

**Comment by westandskif** [comment]
I've contemplated the idea of rating mirrors using timers and I don't think this solves any issue :/

Set its cadence to any value, e.g. weekly like reflector and in the worst case you get a mirrorlist, which is 1 week old. And of course, there will be no guarantee that the mirror, sitting on top of your mirrorlist, is not syncing now or it's too outdated (not to mention it can be slow now).

To use a fresh mirrorlist, you would need to run the timer at least daily, but then imagine a case where all arch users across the globe have timers like this. It would put unnecessary load on mirrors because not 100% of people update their systems daily.

So, this doesn't seem to be a problem, which should be solved with periodic tasks. It feels like the most natural way to use the tool is to either set up an alias to run both rate mirrors and system update at once OR disregard mirror freshness and rate mirrors only when speeds are low.

And of course, should anyone absolutely need a timer like that, it won't be a problem to create it and probably even re-package [rate-mirrors-bin on AUR](https://aur.archlinux.org/packages/rate-mirrors-bin), adding a timer to it.

**Comment by westandskif** [comment]
I do not want to contribute to a code which burns resources just because it's easy to set it up this way. Someone will set it up weekly and will update the system every 2 months.

Secondly, I don't have to convince you or look for excuses, as you said, -- no one forces you to use the tool or prevents you from setting up anything yourself.
