### ISSUE TITLE
[Feature Request] Print comments to STDERR instead of STDOUT

### ISSUE THREAD

**Issue by m00nwtchr** [westandskif/rate-mirrors#57]
Use case: keeping logging to console out while redirecting the mirrorlist output, e.g. to `sudo tee`

**Comment by westandskif** [comment]
Hi! Comments are part of the output by default, so it makes sense to keep pushing them to STDOUT.
Should anyone need to (_not sure why, since they don't interfere with pacman_):
* omit them completely, there's `--disable-comments` option
* omit them in the output file, there are options for it: `rate-mirrors arch --save=abc.txt --disable-comments-in-file arch`

```
      --save <SAVE_TO_FILE>
          Filename to save the output to in case of success

          [env: RATE_MIRRORS_SAVE=]

      --disable-comments
          Disable printing comments

          [env: RATE_MIRRORS_DISABLE_COMMENTS=]

      --disable-comments-in-file
          Disable printing comments to output file

          [env: RATE_MIRRORS_DISABLE_COMMENTS_IN_FILE=]
```
