### ISSUE TITLE
[Feature Request] Weekly Auto Rate the Mirrors 

### ISSUE THREAD

**Issue by abhijeet-singh800** [westandskif/rate-mirrors#60]
I have been using it as a replacement for the [Reflector](https://wiki.archlinux.org/title/Reflector) and now the thing that reflector does is that it has a `systemd` service that regenerates the mirror list weekly and it would be nice to see that with this repository too.

**Comment by abhijeet-singh800** [comment]
Reflector uses a systemd timer unit that runs the service weekly , here is the time unit file 
```ini
[Unit]
Description=Refresh Pacman mirrorlist weekly with Reflector.

[Timer]
OnCalendar=weekly
Persistent=true
AccuracySec=1us
RandomizedDelaySec=12h

[Install]
WantedBy=timers.target
```

**Comment by westandskif** [comment]
hi @abhijeet-singh800 
Thank you for your suggestion! Please, have a look [at this comment](https://github.com/westandskif/rate-mirrors/issues/54#issuecomment-1817922314).
So, I believe this would be a destructive feature, putting unnecessary load on arch's and other mirrors. That's why I haven't added it.
